### ISSUE TITLE
nss indexing does not appear to work

### ISSUE THREAD

**Issue by Liareth** [PhilippeChab/nwscript-ee-language-server#24]
I've had great success with nwscript indexing and completion and code formatting but nss indexing for my code does not appear to work!

![image](https://user-images.githubusercontent.com/9421831/180475803-6e0d4b6c-8987-4f9d-9a39-a7121a1da29e.png)

![image](https://user-images.githubusercontent.com/9421831/180475699-cb276983-d00c-457d-b7d9-81bce3db46e5.png)

I'd love to debug this myself but I'm not quite sure where to start. I didn't see any obvious errors anywhere in VSCode to indicate there might be an issue.

**Comment by Daztek** [comment]
You need a function declaration like `int return_1();` and then it'll work

**Comment by PhilippeChab** [comment]
As Daz said, only functions with a declaration provide intellisense when included in an other file.

**Comment by Liareth** [comment]
Thanks! But unfortunately it did not work for me:

![nocompletion1](https://user-images.githubusercontent.com/9421831/180597058-a7335253-d6c8-4076-8930-86e1b35c46a9.png)

Neither does struct completion, even in the same file:

![nocompletion2](https://user-images.githubusercontent.com/9421831/180597117-de41f07a-2cee-4058-abb4-94ba337a2494.png)

![nocompletion3](https://user-images.githubusercontent.com/9421831/180597118-8c8bce18-de94-4d62-a2fd-f49b360d12e5.png)

This is on a fresh install of VS Code with the latest plugin. I've also never seen the "indexing files..." prompt that the README shows, even when opening a very large codebase. Is it possible I have to enable or activate something within VSCode other than installing the plugin? These are my settings:

```json
{
    "nwscript-ee-lsp.autoCompleteFunctionsWithParams": true,
    "nwscript-ee-lsp.includeCommentsInFunctionsHover": true,
    "nwscript-ee-lsp.formatter": {
        "enabled": true,
        "executable": "clang-format"
    },
    "files.associations": {
        "*.nss": "nwscript"
    },
    "[nwscript]": {
        "editor.defaultFormatter": "PhilippeChab.nwscript-ee-language-server",
        "editor.formatOnSave": true,
    },
    "editor.detectIndentation": false,
}
```

**Comment by Liareth** [comment]
Note: Function intellisense does appear to work within the same file:

![image](https://user-images.githubusercontent.com/9421831/180597271-1d4ef6c6-d3e5-4190-80a4-145d5f33084c.png)

**Comment by Liareth** [comment]
I also tried on my work computer just now and got the same result following these steps:

* Install VSCode
* Start VSCode, install plugin
* Open empty folder
* Create `main.nss`

```c
#include "inc_main.nss"

void main()
{
}

```

* Create `inc_main.nss`

```c
int return_1();

int return_1() { return 1; }

```
* No auto completion in `main.nss` for function in `inc_main.nss` nor for structs defined in `main.nss`.

**Comment by Daztek** [comment]
Oh, you need to do `#include "inc_main"` with the extension

**Comment by Liareth** [comment]
Thanks Daz. Ignore me, I'm just an idiot who is apparently trying her best to violate every single rule of nwscript.
