### ISSUE TITLE
[Autocomplete] Prioritize 'else' over NWScript functions

### ISSUE THREAD

**Issue by Aschent89** [PhilippeChab/nwscript-ee-language-server#25]
Current state:
![image](https://user-images.githubusercontent.com/42368518/180619752-c94d05c1-4c43-480c-a438-4915c63538ff.png)

Hitting enter or tab autocompletes to `EffectSleep`. Ideally would/should prioritize `else` instead of NWScript options.

**Comment by PhilippeChab** [comment]
The `CompletionItemsProvider` does not return any of the language's control keywords. I've asked myself if it actually should during the implementation, and after considering the facts that a) this is something no other language LSP does, b) there is already plenty of completion items to deal with for vscode with the global scope of nwscript and c) we don't really need control keywords as completion items as they are quick to write and not something we will tend to forget, I've decided not to add them.

Same goes for the language basic types, directives, etc.
