### ISSUE TITLE
Diagnostics compiler error on Windows

### ISSUE THREAD

**Issue by Liareth** [PhilippeChab/nwscript-ee-language-server#30]
```
[Info  - 13:53:05] Compiling inc_armor_ed.nss:
[Info  - 13:53:05] Usage: version -128-NOTFOUND.-128-NOTFOUND.-128-NOTFOUND - built Jul 28 2022 02:55:26
[Error - 13:53:05] Unable to resolve nwscript.nss. Are your Neverwinter Nights home and/or installation directories valid?
```

The home and install directories are set correctly. I added some debug text to the package: `this.server.logger.error(args.toString());` which outputs: `[Error - 13:53:05] -y,-c,-l,-r,SKIP_OUTPUT,-h,"C:/Users/Lia/Documents/Neverwinter Nights",-n,"C:/Program Files (x86)/Steam/steamapps/common/Neverwinter Nights",-i,,"d:\neverwinter-zombies\src\gui\inc_armor_ed.nss"`

It's missing the -i, for whatever reason ```args.push([...new Set(paths.map((path) => `"${dirname(path)}"`))].join(";"));``` is returning empty, at least for me on Windows. I hardcoded the path for now which fixed it for me. Maybe it's something local for me, I'm not blocked by this because I was able to hack around it. Just wanted to report the bug in case others experience it too.

**Comment by PhilippeChab** [comment]
Hey Liareth!

Actually, your home and installation directories doesn't seem to be valid if you are on windows. They should print with backslashes, just like the path of you file being compiled `d:\neverwinter-zombies\src\gui\inc_armor_ed.nss`. There is an [example](https://github.com/PhilippeChab/nwscript-ee-language-server#diagnostics-1) in the README.

Hope this fixes it.

**Comment by Liareth** [comment]
Hah, that did actually fix it, thank you! I'm quite surprised because forward slashes USUALLY work on Windows for everything so I'm in the habit of using them. I just replaced the forward slashes with double back slashes and everything started working magically.
