### ISSUE TITLE
More nw_inc_nui shenanigans!

### ISSUE THREAD

**Issue by Liareth** [PhilippeChab/nwscript-ee-language-server#34]
The bug reported in #31 is now fixed, excellent and great work! Unfortunately I've run into a second issue now:

```
[Info  - 11:27:44] Compiling inc_char_ed.nss:
[Info  - 11:27:44] Loading base game resources...
[Info  - 11:27:44] nw_inc_nui.nss(50): Error: NSC1040: Syntax error at "json"
[Info  - 11:27:44] nw_inc_nui.nss(73): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(80): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(88): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(98): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(105): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(113): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(124): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(130): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(136): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(143): Error: NSC1040: Syntax error at "�"
[Info  - 11:27:44] nw_inc_nui.nss(150): Error: NSC1040: Syntax error at "�"
```

On and on until the compiler hits 100 errors. When I compile this file with nwnsc manually it succeeds. I also don't encounter these errors when I'm editing a file which does use json but does not include `nw_inc_nui` - I tested it because I had a suspicion that it was compiling in 1.69 mode, but it turns out not to be (at least for my script, maybe internally it's compiling the include in 1.69 mode?).

**Comment by PhilippeChab** [comment]
Hm. This is weird. Hard to say at a glance, but it would look like the encoding of the file itself is broken or something.

I have no problem compiling `nw_inc_nui .nss` myself from the repo, either in standalone mode or when the file is included in an other file.

Could it be because of your symlink to the `/ovr` folder?

**Comment by Liareth** [comment]
`Could it be because of your symlink to the /ovr folder?` That's interesting - no it isn't, but it set me down a path which led to me discovering more about the problem.

I have two symlinks in my root project folder:

`base_scripts` - this points to a folder containing all of the scripts as extracted from `base_scripts.bif`.
`base_ovr` - this points to ovr, containing `nw_inc_nui`.

Now, interestingly, it isn't the `ovr` symlink that's causing this issue - it's the `base_scripts` symlink! (even though `nw_inc_nui` is not in that folder). This led me down a rabbit hole: including *any* header from the base scripts in one of my scripts, when I have that symlink set up, causes a build error.

![wtf1](https://user-images.githubusercontent.com/9421831/182027990-5b0c5c07-d278-42de-a854-2705d82a24fb.png)

![wtf2](https://user-images.githubusercontent.com/9421831/182027997-c4d165be-e2ef-4cb7-a7ec-ef7a219c9a11.png)

Now this is bizarre, but it isn't where the bizareness ends. Because look what happens when I add a comment next to the include:

![wtf3](https://user-images.githubusercontent.com/9421831/182028009-1644556e-04d8-4bda-a7f3-296a8b837af9.png)

It appears that whenever I include a file from the base game, when it is included in my workspace, it causes the entire file that I'm building to compile in 1.69 mode (without support for json).

At this point I was lost, so I started binary chopping the base_scripts folder (my favourite activity!). At was at this point that I discovered `base_scripts.bif` contains a very old version of `nwscript.nss`. Deleting that file fixed the problem. I think the LSP was noticing that one of the scripts originated from my workspace, so it was adding the file's folder to the include path - which was causing some weird stuff to happen inside the compiler since it was seeing two `nwscript.nss` files (one in `base_scripts` and one in `base_ovr`).

I think this could be fixed in this case by adding a list of paths that could be included for auto completion purposes but not passed as `-I` to the compiler. Not sure if it's worth though - am I the only one that will run into this? Maybe/probably? And it's redundant if #28 gets implemented.

**Comment by PhilippeChab** [comment]
Nice troubleshooting!

> At this point I was lost, so I started binary chopping the base_scripts folder (my favourite activity!). 

That one made me laugh. 😄 

> Deleting that file fixed the problem. I think the LSP was noticing that one of the scripts originated from my workspace, so it was adding the file's folder to the include path - which was causing some weird stuff to happen inside the compiler since it was seeing two nwscript.nss files (one in base_scripts and one in base_ovr).

Yeah that's probably it. What we do is fetch all the file includes recursively, then format it for the the compiler `-i` parameter. Since the directories were supplied to the compiler, most probably it looked them up to try to detect `nwscript.nss` and it conflicted with the one it is normally using.

> I think this could be fixed in this case by adding a list of paths that could be included for auto completion purposes but not passed as -I to the compiler.

We can't really do that since the compiler needs them to resolve includes. 

As you said, since we will implement #28 eventually, this is probably redundant. I will close the issue, feel free to reopen it if you feel something was missed.
