### ISSUE TITLE
Constants highlighting does not recognize operators

### ISSUE THREAD

**Issue by tinygiant98** [PhilippeChab/nwscript-ee-language-server#44]
When a user does not put a space between the constant name and the operator (`=`), the entire line, including the semi-color is considered to be a single token.  Possibly a regex issue.

![image](https://user-images.githubusercontent.com/56231301/185817742-10b4bfda-abab-4b55-b988-c4fa4103b709.png)

This behavior is only present if the qualifier `const` is used.  Otherwise, tokens are identified correctly.

**Comment by PhilippeChab** [comment]
Thanks for reporting this! 

It will be fixed in 1.5.3.
