### ISSUE TITLE
Error detail no longer reported in 1.5.3

### ISSUE THREAD

**Issue by tinygiant98** [PhilippeChab/nwscript-ee-language-server#45]
It appears that error detail is no longer being reported in 1.5.3.

This is error-reporting detail in 1.5.2, caused by a missing semi-colon on line 126:
![image](https://user-images.githubusercontent.com/56231301/185828275-3d7c0a40-a53f-4f16-aa44-2accf17b4eae.png)

This is error-reporting behavior in 1.5.3 on the same file:
![image](https://user-images.githubusercontent.com/56231301/185828481-3b0e170a-5ef1-4b44-b11a-38fd70068ab1.png)

**Comment by PhilippeChab** [comment]
1.5.3 is not released yet!

**Comment by PhilippeChab** [comment]
@tinygiant98 I just released it, if the issue is still present, feel free to reopen the issue. :)
