### ISSUE TITLE
Symbol Information Missing.

### ISSUE THREAD

**Issue by ReachPW** [PhilippeChab/nwscript-ee-language-server#46]
Hi, I've been using your plugin for awhile now and really love it!  It makes scripting in NWN so much fun.

One feature that would be nice is [outlines](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view) and [breadcrumbs](https://code.visualstudio.com/docs/editor/editingevolved#_breadcrumbs).  Currently, it says "No Symbols found in document XYZ.nss".  I'm not too familiar with vscode or plugins, but I think that information comes from a "Symbols provider" from the language server ?

Again, sorry for lack of technical knowledge, but outlines and breadcrumbs would be a nice feature if possible.

Thanks for consideration.

**Comment by PhilippeChab** [comment]
Hey!

Those would be nice additions. :)

I'm currently pretty busy with other stuff however, but I would be happy to implement those if I have some free time. 

Also, if anyone else wishes to fork the project and open a PR, feel free to do so.

**Comment by ReachPW** [comment]
I'm not a TS/node developer, but did find some more information: https://stackoverflow.com/questions/57131265/how-to-add-elements-to-outline-panel-in-custom-extension

**Comment by PhilippeChab** [comment]
@ReachPW I've started implementing something. Seems promising so far.

Little preview.

![Image from Gyazo](https://i.gyazo.com/7f9ae9fcc464fc5ae5149699cbe440f6.png)

**Comment by ReachPW** [comment]
This is very nice!  It really does makes moving around large files so much easier.  Thank you so much! :100:
