### ISSUE TITLE
Add support for r/R string litterals

### ISSUE THREAD

**Issue by ReachPW** [PhilippeChab/nwscript-ee-language-server#65]
the nwn_script_comp added a new feature: 

https://nwn.beamdog.net/docs/#88819336-8---2023-12-10

> Added nwscript support for raw string literals: r".." and R"..", which can also span multiple lines.

The formatter appears to be adding a space between the R and quote.  Ie, should be:

`R"`, but formatter formats it to `R "` which causes problems with the compiler.

**Comment by PhilippeChab** [comment]
When formatting, the language server simply forwards the file content and the arguments to the clang format executable.

I would recommend playing around with the [config](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) to see if there is something that allows string literals of this format.

If nothing seems to do the job, you can always disable formatting for specific patterns, or disable it altogether.
